<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4e80bad6707523e0bd6fac4d79827015
{
    public static $prefixLengthsPsr4 = array (
        'a' => 
        array (
            'app\\' => 4,
        ),
        'R' => 
        array (
            'Root\\Application\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'app\\' => 
        array (
            0 => __DIR__ . '/../..' . '/',
        ),
        'Root\\Application\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4e80bad6707523e0bd6fac4d79827015::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4e80bad6707523e0bd6fac4d79827015::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4e80bad6707523e0bd6fac4d79827015::$classMap;

        }, null, ClassLoader::class);
    }
}
